### ISSUE TITLE
评论的时候必须点击到 github issue 页面才可以吗？

### ISSUE THREAD

**Issue by Gaohaoyang** [nimojs/github-comments#3]
我看到另一个方案

[Gitment：使用 GitHub Issues 搭建评论系统](https://imsun.net/posts/gitment-introduction/)

可以直接在文章页进行评论，github 有相应的 api 吧

我还没有仔细研究，但觉得很棒。

**Comment by nimojs** [comment]
@Gaohaoyang 对着api写应该可以直接在文章也评论的。

Gitment 需要 
```
 oauth: {
    client_id: '你的 client ID',
    client_secret: '你的 client secret',
  }
```
需要完整功能建议用 gitment ，只想挂个评论列表可以用 github-comments

**Comment by YouthJourney** [comment]
这样也行么
